import { Category, Transaction, DebtSummary, DebtPayment } from './supabase/types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Supermercado', type: 'expense', icon: 'ShoppingCart', color: '#10b981' },
  { id: 'cat-2', name: 'Salidas y Comida', type: 'expense', icon: 'Utensils', color: '#f59e0b' },
  { id: 'cat-3', name: 'Servicios e Impuestos', type: 'expense', icon: 'Receipt', color: '#6366f1' },
  { id: 'cat-4', name: 'Transporte y Combustible', type: 'expense', icon: 'Car', color: '#3b82f6' },
  { id: 'cat-5', name: 'Indumentaria', type: 'expense', icon: 'Shirt', color: '#ec4899' },
  { id: 'cat-6', name: 'Tecnología y Gadgets', type: 'expense', icon: 'Laptop', color: '#8b5cf6' },
  { id: 'cat-7', name: 'Salud y Farmacia', type: 'expense', icon: 'HeartPulse', color: '#ef4444' },
  { id: 'cat-8', name: 'Entretenimiento', type: 'expense', icon: 'Tv', color: '#14b8a6' },
  { id: 'cat-9', name: 'Educación', type: 'expense', icon: 'GraduationCap', color: '#f97316' },
  { id: 'cat-10', name: 'Otros Gastos', type: 'expense', icon: 'MoreHorizontal', color: '#64748b' },
  { id: 'cat-11', name: 'Sueldo', type: 'income', icon: 'DollarSign', color: '#10b981' },
  { id: 'cat-12', name: 'Ventas', type: 'income', icon: 'Tag', color: '#f59e0b' },
  { id: 'cat-13', name: 'Honorarios', type: 'income', icon: 'Briefcase', color: '#06b6d4' },
  { id: 'cat-14', name: 'Transferencia', type: 'income', icon: 'ArrowRightLeft', color: '#3b82f6' },
  { id: 'cat-15', name: 'Otros Ingresos', type: 'income', icon: 'TrendingUp', color: '#14b8a6' },
  { id: 'cat-16', name: 'Deudas', type: 'expense', icon: 'HandCoins', color: '#f97316' },
  { id: 'cat-17', name: 'Cobro Deudas', type: 'income', icon: 'HandCoins', color: '#10b981' },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    type: 'expense',
    amount: 18500,
    currency: 'ARS',
    category_id: 'cat-1',
    date: '2026-09-28',
    note: 'Coto compras semanales',
    payment_method: 'tarjeta_debito',
    installment_current: null,
    installment_total: null,
    parent_transaction_id: null,
    created_at: '2026-09-28T11:20:00Z',
  },
  {
    id: 'tx-2',
    type: 'expense',
    amount: 25,
    currency: 'USD',
    category_id: 'cat-6',
    date: '2026-09-27',
    note: 'Hosting Vercel Pro & Dominio',
    payment_method: 'tarjeta_credito',
    installment_current: null,
    installment_total: null,
    parent_transaction_id: null,
    created_at: '2026-09-27T15:10:00Z',
  },
  {
    id: 'tx-3',
    type: 'expense',
    amount: 9200,
    currency: 'ARS',
    category_id: 'cat-2',
    date: '2026-09-26',
    note: 'Almuerzo con equipo',
    payment_method: 'efectivo',
    installment_current: null,
    installment_total: null,
    parent_transaction_id: null,
    created_at: '2026-09-26T13:45:00Z',
  },
  {
    id: 'tx-4',
    type: 'expense',
    amount: 20000,
    currency: 'ARS',
    category_id: 'cat-5',
    date: '2026-09-15',
    note: 'Zapatillas Adidas (Cuota 1/3)',
    payment_method: 'tarjeta_credito',
    installment_current: 1,
    installment_total: 3,
    parent_transaction_id: 'tx-parent-cuota-1',
    created_at: '2026-09-15T10:00:00Z',
  },
  {
    id: 'tx-5',
    type: 'expense',
    amount: 20000,
    currency: 'ARS',
    category_id: 'cat-5',
    date: '2026-10-15',
    note: 'Zapatillas Adidas (Cuota 2/3)',
    payment_method: 'tarjeta_credito',
    installment_current: 2,
    installment_total: 3,
    parent_transaction_id: 'tx-parent-cuota-1',
    created_at: '2026-09-15T10:00:00Z',
  },
  {
    id: 'tx-6',
    type: 'expense',
    amount: 20000,
    currency: 'ARS',
    category_id: 'cat-5',
    date: '2026-11-15',
    note: 'Zapatillas Adidas (Cuota 3/3)',
    payment_method: 'tarjeta_credito',
    installment_current: 3,
    installment_total: 3,
    parent_transaction_id: 'tx-parent-cuota-1',
    created_at: '2026-09-15T10:00:00Z',
  },
  {
    id: 'tx-7',
    type: 'expense',
    amount: 35000,
    currency: 'ARS',
    category_id: 'cat-6',
    date: '2026-09-10',
    note: 'Monitor Dell 27 (Cuota 2/6)',
    payment_method: 'tarjeta_credito',
    installment_current: 2,
    installment_total: 6,
    parent_transaction_id: 'tx-parent-cuota-2',
    created_at: '2026-08-10T10:00:00Z',
  },
  {
    id: 'tx-8',
    type: 'expense',
    amount: 35000,
    currency: 'ARS',
    category_id: 'cat-6',
    date: '2026-10-10',
    note: 'Monitor Dell 27 (Cuota 3/6)',
    payment_method: 'tarjeta_credito',
    installment_current: 3,
    installment_total: 6,
    parent_transaction_id: 'tx-parent-cuota-2',
    created_at: '2026-08-10T10:00:00Z',
  },
  {
    id: 'tx-9',
    type: 'expense',
    amount: 35000,
    currency: 'ARS',
    category_id: 'cat-6',
    date: '2026-11-10',
    note: 'Monitor Dell 27 (Cuota 4/6)',
    payment_method: 'tarjeta_credito',
    installment_current: 4,
    installment_total: 6,
    parent_transaction_id: 'tx-parent-cuota-2',
    created_at: '2026-08-10T10:00:00Z',
  },
  {
    id: 'tx-10',
    type: 'expense',
    amount: 35000,
    currency: 'ARS',
    category_id: 'cat-6',
    date: '2026-12-10',
    note: 'Monitor Dell 27 (Cuota 5/6)',
    payment_method: 'tarjeta_credito',
    installment_current: 5,
    installment_total: 6,
    parent_transaction_id: 'tx-parent-cuota-2',
    created_at: '2026-08-10T10:00:00Z',
  },
  {
    id: 'tx-11',
    type: 'expense',
    amount: 35000,
    currency: 'ARS',
    category_id: 'cat-6',
    date: '2027-01-10',
    note: 'Monitor Dell 27 (Cuota 6/6)',
    payment_method: 'tarjeta_credito',
    installment_current: 6,
    installment_total: 6,
    parent_transaction_id: 'tx-parent-cuota-2',
    created_at: '2026-08-10T10:00:00Z',
  },
  {
    id: 'tx-12',
    type: 'income',
    amount: 950000,
    currency: 'ARS',
    category_id: 'cat-11',
    date: '2026-09-01',
    note: 'Sueldo mensual neto',
    payment_method: 'transferencia',
    installment_current: null,
    installment_total: null,
    parent_transaction_id: null,
    created_at: '2026-09-01T09:00:00Z',
  },
  {
    id: 'tx-13',
    type: 'income',
    amount: 600,
    currency: 'USD',
    category_id: 'cat-12',
    date: '2026-09-05',
    note: 'Proyecto Frontend Landing Page',
    payment_method: 'transferencia',
    installment_current: null,
    installment_total: null,
    parent_transaction_id: null,
    created_at: '2026-09-05T12:00:00Z',
  },
  {
    id: 'tx-14',
    type: 'expense',
    amount: 14500,
    currency: 'ARS',
    category_id: 'cat-3',
    date: '2026-09-12',
    note: 'Internet Fibra 300Mb',
    payment_method: 'transferencia',
    installment_current: null,
    installment_total: null,
    parent_transaction_id: null,
    created_at: '2026-09-12T16:00:00Z',
  },
  {
    id: 'tx-15',
    type: 'expense',
    amount: 12000,
    currency: 'ARS',
    category_id: 'cat-4',
    date: '2026-09-18',
    note: 'Carga Nafta YPF',
    payment_method: 'tarjeta_debito',
    installment_current: null,
    installment_total: null,
    parent_transaction_id: null,
    created_at: '2026-09-18T08:30:00Z',
  },
];

export const INITIAL_DEBTS: DebtSummary[] = [
  {
    id: 'debt-1',
    type: 'owed',
    person_name: 'Juan Perez',
    total_amount: 50000,
    currency: 'ARS',
    status: 'active',
    note: 'Préstamo entradas recital',
    created_at: '2026-08-20T14:00:00Z',
    total_paid: 20000,
    remaining_amount: 30000,
    payments: [
      {
        id: 'pay-1',
        debt_id: 'debt-1',
        amount: 20000,
        date: '2026-09-10',
        note: 'Transferencia bancaria parte 1',
        created_at: '2026-09-10T11:00:00Z',
      },
    ],
  },
  {
    id: 'debt-2',
    type: 'owed',
    person_name: 'Martin Gonzalez',
    total_amount: 150,
    currency: 'USD',
    status: 'active',
    note: 'Comisión diseño compartida',
    created_at: '2026-09-02T16:30:00Z',
    total_paid: 50,
    remaining_amount: 100,
    payments: [
      {
        id: 'pay-2',
        debt_id: 'debt-2',
        amount: 50,
        date: '2026-09-15',
        note: 'Pago en crypto USDT',
        created_at: '2026-09-15T18:00:00Z',
      },
    ],
  },
  {
    id: 'debt-3',
    type: 'owe',
    person_name: 'Mecánico Carlos',
    total_amount: 85000,
    currency: 'ARS',
    status: 'active',
    note: 'Reparación frenos y cambio de aceite',
    created_at: '2026-09-22T09:15:00Z',
    total_paid: 35000,
    remaining_amount: 50000,
    payments: [
      {
        id: 'pay-3',
        debt_id: 'debt-3',
        amount: 35000,
        date: '2026-09-22',
        note: 'Seña inicial en efectivo',
        created_at: '2026-09-22T09:20:00Z',
      },
    ],
  },
  {
    id: 'debt-4',
    type: 'owed',
    person_name: 'Laura V.',
    total_amount: 15000,
    currency: 'ARS',
    status: 'settled',
    note: 'Cena cumpleaños compartida',
    created_at: '2026-08-01T22:00:00Z',
    total_paid: 15000,
    remaining_amount: 0,
    payments: [
      {
        id: 'pay-4',
        debt_id: 'debt-4',
        amount: 15000,
        date: '2026-08-05',
        note: 'MercadoPago',
        created_at: '2026-08-05T10:00:00Z',
      },
    ],
  },
];
